name: uk_weather
version: "1.0.0"
config-version: 2

profile: uk_weather

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  uk_weather:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
