uk_weather:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: pipeline_user
      password: pipeline_pass
      dbname: weather_db
      schema: transformed
      threads: 4
