FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip \
    && pip install dbt-postgres==1.7.17 psycopg2-binary

WORKDIR /usr/app/dbt

ENTRYPOINT ["tail", "-f", "/dev/null"]
